### ISSUE TITLE
Loot Tables Empty

### ISSUE THREAD

**Issue by ereese99** [Hir0shiyt/Trident-Crafting-And-Structures-2#1]
The loot tables on this mod don't work

**Comment by Hir0shiyt** [comment]
What version of the mod are you using?

**Comment by Hir0shiyt** [comment]
I'm sorry for the late reply, i've been feeling sick

**Comment by ereese99** [comment]
TCS2_1.19.2_1.0.2_FABRIC.jar

**Comment by Hir0shiyt** [comment]
Gonna fix it right now

**Comment by Hir0shiyt** [comment]
Fixed!

**Comment by ereese99** [comment]
Nice! I see the changelog, but when I go to play with it, I get this crash:
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'TCAndS_II_fabric' (tcands_ii_fabric) 1.0.4 with any version that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'TCAndS_II_fabric' (tcands_ii_fabric) 1.0.4 requires any version between 1.18 (inclusive) and 1.19- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by ereese99** [comment]
Note: I'm using Minecraft 1.19.2, Fabric 0.14.13

**Comment by Hir0shiyt** [comment]
uhhh

**Comment by Hir0shiyt** [comment]
Fixing back again

**Comment by Hir0shiyt** [comment]
Here you have the early download fixed now
https://www.mediafire.com/file/7ni1y3g6tg4uk15/TCS2_1.19.2_1.0.4_FABRIC.jar/file

**Comment by ereese99** [comment]
Awesome! Thanks!
